// Generated by morphir-elm

import { Morphir_IR_Name_Name } from "../../morphir/ir/Name"
import { Morphir_IR_Path_Path } from "../../morphir/ir/Path"

/* Type that represents a fully-qualified name.
The parameters are PackagePath ModulePath Name
*/
export type Morphir_IR_FQName_FQName = [Morphir_IR_Path_Path, Morphir_IR_Path_Path, Morphir_IR_Name_Name]
