// Generated by morphir-elm

import { Morphir_SDK_Char_Char } from "../../morphir/sdk/Char"

/* Type that represents a literal value.
*/
export type Morphir_IR_Literal_Literal = BoolLiteral | CharLiteral | FloatLiteral | StringLiteral | WholeNumberLiteral

interface Morphir_IR_Literal_BoolLiteral{
  kind: "BoolLiteral";
  arg1: boolean;
}

interface Morphir_IR_Literal_CharLiteral{
  kind: "CharLiteral";
  arg1: Morphir_SDK_Char_Char;
}

interface Morphir_IR_Literal_FloatLiteral{
  kind: "FloatLiteral";
  arg1: number;
}

interface Morphir_IR_Literal_StringLiteral{
  kind: "StringLiteral";
  arg1: string;
}

interface Morphir_IR_Literal_WholeNumberLiteral{
  kind: "WholeNumberLiteral";
  arg1: number;
}
