// Generated by morphir-elm

import { Morphir_IR_AccessControlled_AccessControlled } from "../../morphir/ir/AccessControlled"
import { Morphir_IR_Documented_Documented } from "../../morphir/ir/Documented"
import { Morphir_IR_Name_Name } from "../../morphir/ir/Name"
import { Morphir_IR_Path_Path } from "../../morphir/ir/Path"
import { Morphir_IR_Type_Definition } from "../../morphir/ir/Type"
import { Morphir_IR_Type_Specification } from "../../morphir/ir/Type"
import { Morphir_IR_Value_Definition } from "../../morphir/ir/Value"
import { Morphir_IR_Value_Specification } from "../../morphir/ir/Value"

/* Type that represents a module definition. A module definition contains all the details
including implementation and private types and values.

A module contains types and values which is represented by two field in this type:

  - types: a dictionary of local name to access controlled, documented type specification.
  - values: a dictionary of local name to access controlled value specification.

*/
export type Morphir_IR_Module_Definition<ta, va> = {
  Types: Array<[Morphir_IR_Name_Name, Morphir_IR_AccessControlled_AccessControlled<Morphir_IR_Documented_Documented<Morphir_IR_Type_Definition<ta>>>]>;
  Values: Array<[Morphir_IR_Name_Name, Morphir_IR_AccessControlled_AccessControlled<Morphir_IR_Value_Definition<ta, va>>]>;
}

/* A module name is a unique identifier for a module within a package. It is represented by a path, which is a list of
names.
*/
export type Morphir_IR_Module_ModuleName = Morphir_IR_Path_Path

/* Type that represents a module specification. A module specification only contains types that are exposed
publicly and type signatures for values that are exposed publicly.

A module contains types and values which is represented by two field in this type:

  - types: a dictionary of local name to documented type specification.
  - values: a dictionary of local name to value specification.

*/
export type Morphir_IR_Module_Specification<ta> = {
  Types: Array<[Morphir_IR_Name_Name, Morphir_IR_Documented_Documented<Morphir_IR_Type_Specification<ta>>]>;
  Values: Array<[Morphir_IR_Name_Name, Morphir_IR_Value_Specification<ta>]>;
}
