// Generated by morphir-elm

import { Morphir_IR_Name_Name } from "../../morphir/ir/Name"

/* Type that represents a path as a list of names.
*/
export type Morphir_IR_Path_Path = Array<Morphir_IR_Name_Name>
