// Generated by morphir-elm

import { Morphir_IR_Name_Name } from "../../morphir/ir/Name"
import { Morphir_IR_Path_Path } from "../../morphir/ir/Path"

interface Morphir_IR_QName_QName{
  kind: "QName";
  arg1: Morphir_IR_Path_Path;
  arg2: Morphir_IR_Name_Name;
}
